[GLOBAL] 
pants_version = "2.11.0"

backend_packages = [
  "pants.backend.experimental.java",
  "pants.backend.experimental.java.lint.google_java_format",
  #"pants.backend.experimental.java.debug_goals",
  "pants.backend.experimental.scala",
  "pants.backend.experimental.scala.lint.scalafmt",
  #"pants.backend.experimental.scala.debug_goals",
]

[coursier]
repos = [
  "https://maven-central.storage-download.googleapis.com/maven2",
  "https://repo1.maven.org/maven2",
  "https://oss.sonatype.org/content/repositories/snapshots",
]

[javac]
args = [
  "-deprecation",
  "-encoding UTF-8",
]

[scalac]
args = [
  "-Xsource:3",
  "-Ylog-classpath",
  "-deprecation",
  "-encoding UTF-8",
  "-feature",
  "-Ymacro-annotations",
  "-language:implicitConversions",
  "-language:higherKinds",
  "-language:existentials",
  "-Wconf:cat=other-match-analysis:error",
  "-Xfatal-warnings",
  "-Xlint:adapted-args",
]

#plugins_for_resolve = { "jvm-default" = "deriving,bm4,kind-projector" }

[scala]
version_for_resolve = { "jvm-default" = "2.13.6" }

[anonymous-telemetry]
enabled = false

